# This workflow will do a clean install of the dependencies and run tests across different versions
#
# Find Github Actions to setup tooling here:
# - https://github.com/actions/?q=setup&type=&language=
# - https://github.com/actions/starter-workflows/tree/main/ci
# - https://github.com/marketplace?type=actions&query=setup
#
# Requires scripts:
# - scripts/ci-check
# - scripts/ci

name: z3 / main

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  precheck:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python Dependencies
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8

      - name: Install project dependencies
        run: 
          python scripts/mk_make.py -x
          cd build
          pip install z3-solver

      - name: Run exercism/z3 ci pre-check (checks config, lint code) for all exercises
        run: scripts/ci-check

  ci:
    runs-on: ubuntu-16.04

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Use ${{ matrix.version }}
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install python dependencies
        run: python scripts/mk_make.py -x
        
      - name: Enter build
        run: cd build
        
      - name: Install Z3 dependencies
        run: pip install z3-solver

      - name: Run exercism/z3 ci (runs tests) for all exercises
        run: scripts/ci
